### ISSUE TITLE
BadAuxVar

### ISSUE THREAD

**Issue by kratsg** [kratsg/ReclusteringStudies#4]
terminate called after throwing an instance of 'SG::ExcBadAuxVar'
  what():  SG::ExcBadAuxVar: Attempt to retrieve nonexistent aux data item `::originalObjectLink' (0).
Aborted

**Comment by womeansme** [comment]
Hi kratsg, I encountered the same problem like this. Could you give me same hint on how to fix it?

**Comment by kratsg** [comment]
You can see the commit 947b402 that I reference when closing this. In this case, it was because the `switch` statement I was using does not provide initialization before the `case` statements and I had to initialize my static variable accessors before the `switch` closure starts.

**Comment by womeansme** [comment]
Hi Krastsg,

Thanks. It is very helpful. 

----- �������� -----
������: "Giordon Stark" notifications@github.com
������: "kratsg/ReclusteringStudies" ReclusteringStudies@noreply.github.com
����: "womeansme" yonglianghao@sjtu.edu.cn
��������: ������, 2015�� 5 �� 19�� ���� 1:08:00
����: Re: [ReclusteringStudies] BadAuxVar (#4)

You can see the commit 947b402 that I reference when closing this. In this case, it was because the `switch` statement I was using does not provide initialization before the `case` statements and I had to initialize my static variable accessors before the `switch` closure starts.

---
